privacy:
  - "we log your death, inventory, xp, a DNR sample and witnesses if any. funny"
  - "log Killquest winners. nice"
  - "log nicks of those who eat sand or dirt. funny"
  - "log blockrace stuff , what blocks got, when lost, when won. design"
  - "log nickname, world and score on /amiworthy, for cool points when noticed. nice"
  - "log /report <text text text text> , because feedback matters a lot. nice"
  - "will log mail pidgeons sender and recipient, but not the messages. design"
  - "will log /ibuiltdis <nameofthebuild> , name of the builder , location. nice"
  - "will log taverns, builders and tavernblocks as well as the location. nice"
  - "Will = not there yet"
  
