news:
  good:
    - "killquest tracks kills in the area, kill a bunch and hostiles wont spawn"
    - "made the compass work like wanted, it point north i think... negative z"
    - "banning weaklings is on, good for core players"
    - "player can easier detect slimes"
    - "sleeping actually helps, not  just an insomniac chore anymore"
  bad:
    - "you die you get banned until the next month or smt"
    - "when you spawn or respawn its most likely gonna be random"
    - "bye bye fun blockrace for now"
    - "the dude wrote spaghetti code again"
    - "the dude did a 4h minecraft stream and got promised to fail by a stranger"
